language: node_js

node_js:
  - "7"

sudo: false

before_install:
  - pip install --user codecov

cache: yarn

after_success:
  - codecov --file .tmp/coverage/lcov.info --disable search

script: yarn test --runInBand